Text analyzer
vidis01/learning pull request #6
Opened 2024-08-28 18:45 UTC by kulverstux

Counts everything
still missing detailed counting
//not finished yet

2024-08-28 22:21 UTC, vidis01 commented
One more idea to think about program efficiency is to change a little bit program structure:

1. Create private fields for _consonants, _wovels and _punctuations

2. Those Methods: CountWovels, CountConsonants, CountPunctuations join to one method and join all cases under one switch sentence and remove foreach cycle.  When you will have one switch you will be able to increment those fields  _consonants, _wovels, and _punctuations accordingly.

3. This joint method will be used during the file reading process when you analyze every symbol. Then with every symbol you will be able to call this newly joint method which will count what type letter is. In this case, in the while cycle you will be counting without running separate foreach cycles in separate methods and in PrintQuickSummary you just print out those already counted properties _consonants, _wovels, and _punctuations.

If you will implement this change until tomorrow's lecture, we will do so experiments with your unchanged code, and with this improvement. We will measure the whole algorithm's running times and we will compare whether the program becomes faster.
----------------------------------------------------------------
Overall my expectations of this simple task you completed, exceeded my expectations 110%, because of the simple methods, you made a complete and working program which is very nice and actually could be used as stand-alone program.

Again good job and well done. If you have time make all my mentioned changes also we will be able to add unit tests for this program and then we will be max completed. 10/10

2024-08-28 22:24 UTC, vidis01 requested changes

2024-09-02 06:32 UTC, vidis01 approved these changes
![image](https://github.com/user-attachments/assets/2d7ab8ee-0fbb-45b5-9e0c-e22126387a3b)

When fixing previous pull request comments, please mark Resolve conversation, when you add a fix, also it is good to put some words that problem is fixed or if you think that it  is no need to do any changes, just put some motivation why and resolve.

2024-09-03 18:42 UTC, kulverstux commented on Learning/Manto/TextAnalyzer.cs
> +                for (int i = 32; i <= 46; i++)
fixed

2024-09-03 18:44 UTC, merged